# Generated by Django 5.0 on 2025-01-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hrrole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hrrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('required_to_attend', models.IntegerField()),
                ('evaluated', models.IntegerField()),
            ],
            options={
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meetingevaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('attendance', models.CharField(max_length=2)),
                ('task', models.SmallIntegerField()),
                ('performance', models.SmallIntegerField()),
                ('interaction', models.SmallIntegerField()),
                ('behavior', models.SmallIntegerField()),
                ('bonus', models.IntegerField()),
                ('total', models.SmallIntegerField()),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'meetingevaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.SmallIntegerField()),
                ('performance', models.SmallIntegerField()),
                ('interaction', models.SmallIntegerField()),
                ('behavior', models.SmallIntegerField()),
                ('bonus', models.SmallIntegerField()),
                ('total', models.SmallIntegerField()),
                ('attended_meetings', models.SmallIntegerField()),
                ('unattended_meetings', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subteam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_official', models.IntegerField()),
                ('warning_type', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warnings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrroleTeams',
            fields=[
                ('hrrole', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Employees.hrrole')),
            ],
            options={
                'db_table': 'hrrole_teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingSubTeams',
            fields=[
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Employees.meeting')),
            ],
            options={
                'db_table': 'meeting_sub_teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingTeams',
            fields=[
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Employees.meeting')),
            ],
            options={
                'db_table': 'meeting_teams',
                'managed': False,
            },
        ),
    ]
