# Generated by Django 5.0 on 2025-01-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
    ]
