# Generated by Django 5.0 on 2025-01-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_employee_groups_employee_sub_team_employee_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
    ]
